version: "3.6"

services:
  database:
    image: mongo
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=cygni
      - MONGO_INITDB_DATABASE=cts-ng
    volumes:
      - "dbdata:/data/db"
    networks:
      - database
    ports:
      - "27017:27017"
    restart: always

  database_admin:
    depends_on:
      - database
    image: mongo-express
    container_name: database_admin
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_ADMINUSERNAME=cygni
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - database
    ports:
      - "8081:8081"
    restart: always

volumes:
  dbdata:

networks:
  database:
